name: Build & SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_ORG: kozakmikhail1
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Build lab1
        run: |
          rm -rf laboratory_work_1/build
          mkdir laboratory_work_1/build
          cmake -S laboratory_work_1 -B laboratory_work_1/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_1/build_wrapper cmake --build laboratory_work_1/build --config Release

      - name: Build lab3
        run: |
          rm -rf laboratory_work_3/build
          mkdir laboratory_work_3/build
          cmake -S laboratory_work_3 -B laboratory_work_3/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_3/build_wrapper cmake --build laboratory_work_3/build --config Release
      
      - name: Build lab4
        run: |
          rm -rf laboratory_work_4/build
          mkdir laboratory_work_4/build
          cmake -S laboratory_work_4 -B laboratory_work_4/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_4/build_wrapper cmake --build laboratory_work_4/build --config Release
          
      - name: Build lab5
        run: |
          rm -rf laboratory_work_5/build
          mkdir laboratory_work_5/build
          cmake -S laboratory_work_5 -B laboratory_work_5/build 
          build-wrapper-linux-x86-64 --out-dir laboratory_work_5/build_wrapper cmake --build laboratory_work_5/build --config Release

      - name: SonarCloud scan laboratory_work_1
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_1
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_1/src,laboratory_work_1/include
            -Dsonar.cfamily.compile-commands=laboratory_work_1/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true
            -Dsonar.exclusions=**/build/**,**/*.exe
            -Dsonar.issue.ignore.multicriteria=e1
            -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*
            -Dsonar.issue.ignore.multicriteria.e1.ruleKey=cpp:S5025

      - name: SonarCloud scan laboratory_work_3
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_3
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_3/src,laboratory_work_3/include
            -Dsonar.cfamily.compile-commands=laboratory_work_3/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true
            -Dsonar.exclusions=**/build/**,**/*.exe
            -Dsonar.issue.ignore.multicriteria=e1
            -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*
            -Dsonar.issue.ignore.multicriteria.e1.ruleKey=cpp:S5025

      - name: SonarCloud scan laboratory_work_4
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_4
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_4/src,laboratory_work_4/include
            -Dsonar.cfamily.compile-commands=laboratory_work_4/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true
            -Dsonar.exclusions=**/build/**,**/*.exe
            -Dsonar.issue.ignore.multicriteria=e1
            -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*
            -Dsonar.issue.ignore.multicriteria.e1.ruleKey=cpp:S5025

      - name: SonarCloud scan laboratory_work_5
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kozakmikhail1_cpp_lab_5
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=laboratory_work_5/src,laboratory_work_5/include
            -Dsonar.cfamily.compile-commands=laboratory_work_5/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true
            -Dsonar.exclusions=**/build/**,**/*.exe
            -Dsonar.issue.ignore.multicriteria=e1
            -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*
            -Dsonar.issue.ignore.multicriteria.e1.ruleKey=cpp:S5025